spring:
  application:
    name: eureka-server
server:
  port: 2222
eureka:
  instance:
    hostname: eureka-server2
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-server1:1111/eureka/




