spring:
  application:
    name: eureka-server
server:
  port: 1111
eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      default-zone: http://localhost:${server.port}/eureka/


