spring:
  application:
    name: admin-server
  boot:
    admin:
      context-path:  /sba
server:
  port: 10000
  context-path: /monitor/
eureka:
  client:
    service-url:
     default-zone: http://localhost:1111/eureka/