spring:
  jpa:
    database: h2
  datasource:
    data:
      classpath*:/sql/InitData.sql
    schema:
      classpath*:/sql/CreateTables.sql
    continueOnError:
     false
    url:
      jdbc:h2:~/test
logging:
  level:
    root:
      INFO